/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alejo
 */
public class CalculadoraCientifica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraCientifica.class.getName());

    /**
     * Creates new form CalculadoraCientifica
     */
    
    //Variables
    private double num1 = 0.00; 
    private double num2 = 0.00; 
    private double resultado = 0.00; 
    private boolean igual, inicio = true, op1,op2; 
    private String TOperaciones; 
    
    public CalculadoraCientifica() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Principal1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_Principal = new javax.swing.JTextField();
        B_Raiz = new javax.swing.JButton();
        B_Borrar = new javax.swing.JButton();
        B_Limpiar = new javax.swing.JButton();
        B_Porce = new javax.swing.JButton();
        B_7 = new javax.swing.JButton();
        B_8 = new javax.swing.JButton();
        B_9 = new javax.swing.JButton();
        B_Divi = new javax.swing.JButton();
        B_3 = new javax.swing.JButton();
        B_1 = new javax.swing.JButton();
        B_2 = new javax.swing.JButton();
        B_Rest = new javax.swing.JButton();
        B_4 = new javax.swing.JButton();
        B_5 = new javax.swing.JButton();
        B_6 = new javax.swing.JButton();
        B_Multi = new javax.swing.JButton();
        B_Punto = new javax.swing.JButton();
        B_0 = new javax.swing.JButton();
        B_Igual = new javax.swing.JButton();
        B_Sum = new javax.swing.JButton();

        jButton2.setText("0");

        jButton6.setText("0");

        jButton7.setText("0");

        jButton8.setText("0");

        jButton9.setText("0");

        jButton14.setText("0");

        jButton15.setText("0");

        jButton16.setText("0");

        jButton17.setText("0");

        jPanel2.setBackground(new java.awt.Color(129, 129, 129));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jTextField_Principal1.setPreferredSize(new java.awt.Dimension(300, 60));

        jButton10.setText("0");

        jButton11.setText("0");

        jButton12.setText("0");

        jButton13.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField_Principal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jButton18.setText("0");

        jButton19.setText("0");

        jButton20.setText("0");

        jButton21.setText("0");

        jButton22.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(129, 129, 129));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 450));

        jTextField_Principal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Principal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Principal.setEnabled(false);
        jTextField_Principal.setPreferredSize(new java.awt.Dimension(300, 60));

        B_Raiz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Raiz.setText("√");
        B_Raiz.addActionListener(this::B_RaizActionPerformed);

        B_Borrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Borrar.setText("C");
        B_Borrar.addActionListener(this::B_BorrarActionPerformed);

        B_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Limpiar.setText("AC");
        B_Limpiar.addActionListener(this::B_LimpiarActionPerformed);

        B_Porce.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Porce.setText("%");
        B_Porce.addActionListener(this::B_PorceActionPerformed);

        B_7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_7.setText("7");
        B_7.addActionListener(this::B_7ActionPerformed);

        B_8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_8.setText("8");
        B_8.addActionListener(this::B_8ActionPerformed);

        B_9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_9.setText("9");
        B_9.addActionListener(this::B_9ActionPerformed);

        B_Divi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Divi.setText("/");
        B_Divi.addActionListener(this::B_DiviActionPerformed);

        B_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_3.setText("3");
        B_3.addActionListener(this::B_3ActionPerformed);

        B_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_1.setText("1");
        B_1.addActionListener(this::B_1ActionPerformed);

        B_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_2.setText("2");
        B_2.addActionListener(this::B_2ActionPerformed);

        B_Rest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Rest.setText("-");
        B_Rest.addActionListener(this::B_RestActionPerformed);

        B_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_4.setText("4");
        B_4.addActionListener(this::B_4ActionPerformed);

        B_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_5.setText("5");
        B_5.addActionListener(this::B_5ActionPerformed);

        B_6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_6.setText("6");
        B_6.addActionListener(this::B_6ActionPerformed);

        B_Multi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Multi.setText("*");
        B_Multi.addActionListener(this::B_MultiActionPerformed);

        B_Punto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Punto.setText(".");
        B_Punto.addActionListener(this::B_PuntoActionPerformed);

        B_0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_0.setText("0");
        B_0.addActionListener(this::B_0ActionPerformed);

        B_Igual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Igual.setText("=");
        B_Igual.addActionListener(this::B_IgualActionPerformed);

        B_Sum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B_Sum.setText("+");
        B_Sum.addActionListener(this::B_SumActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Rest, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Divi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(B_Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Porce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(B_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextField_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Porce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Divi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Rest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void B_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_0ActionPerformed
       
        if (inicio == true){ 
            jTextField_Principal.setText(""); 
            jTextField_Principal.setText("0"); 
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"0"); 
        }
    }//GEN-LAST:event_B_0ActionPerformed
    
    
    private void B_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_1ActionPerformed
      
        if (inicio == true){ 
            jTextField_Principal.setText("");
            jTextField_Principal.setText("1");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"1");
        }
    }//GEN-LAST:event_B_1ActionPerformed
    
   
    private void B_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_2ActionPerformed
        
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("2");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"2");
        }
    }//GEN-LAST:event_B_2ActionPerformed
    
    
    private void B_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_3ActionPerformed
      
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("3");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"3");
        }
    }//GEN-LAST:event_B_3ActionPerformed

    
    private void B_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_4ActionPerformed
        
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("4");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"4");
        }
    }//GEN-LAST:event_B_4ActionPerformed

   
    private void B_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_5ActionPerformed
        
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("5");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"5");
        }
    }//GEN-LAST:event_B_5ActionPerformed

   
    private void B_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_6ActionPerformed
       
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("6");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"6");
        }
    }//GEN-LAST:event_B_6ActionPerformed

    
    private void B_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_7ActionPerformed
       
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("7");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"7");
        }
    }//GEN-LAST:event_B_7ActionPerformed

    
    private void B_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_8ActionPerformed
       
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("8");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"8");
        }
    }//GEN-LAST:event_B_8ActionPerformed

    
    private void B_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_9ActionPerformed
        
        if (inicio == true){
            jTextField_Principal.setText("");
            jTextField_Principal.setText("9");
            inicio=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"9");
        }
    }//GEN-LAST:event_B_9ActionPerformed

    
    private void B_PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PuntoActionPerformed
        
        if (jTextField_Principal.getText().contains(".")){
           
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+".");
            inicio=false;
        }
    }//GEN-LAST:event_B_PuntoActionPerformed

  
    private void B_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SumActionPerformed
        
        igual= true;
        inicio=true;
        if (op1 = true){ 
            num1=Double.parseDouble(jTextField_Principal.getText()); 
            jTextField_Principal.setText(jTextField_Principal.getText()+"+");
            op1=false; 
        }else{
            if (op2 = true){ 
            num2=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"+");
            op2=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"+");
            Op(resultado,num2);
        }
        }
        TOperaciones = "+"; 
    }//GEN-LAST:event_B_SumActionPerformed

   
    private void B_RestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RestActionPerformed
       
        igual= true;
        inicio=true;
        if (op1 = true){
            num1=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"-");
            op1=false;
        }else{
            if (op2 = true){
            num2=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"-");
            op2=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"-");
            Op(resultado,num2);
        }
        }
        TOperaciones = "-";
    }//GEN-LAST:event_B_RestActionPerformed

    
    private void B_MultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MultiActionPerformed
        
        igual= true;
        inicio=true;
        if (op1 = true){
            num1=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"*");
            op1=false;
        }else{
            if (op2 = true){
            num2=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"*");
            op2=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"*");
            Op(resultado,num2);
        }
        }
        TOperaciones = "*";
    }//GEN-LAST:event_B_MultiActionPerformed

    
    private void B_DiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DiviActionPerformed
        
        igual= true;
        inicio=true;
        if (op1 = true){
            num1=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"/");
            op1=false;
        }else{
            if (op2 = true){
            num2=Double.parseDouble(jTextField_Principal.getText());
            jTextField_Principal.setText(jTextField_Principal.getText()+"/");
            op2=false;
        }else{
            jTextField_Principal.setText(jTextField_Principal.getText()+"/");
            Op(resultado,num2);
        }
        }
        TOperaciones = "/";
    }//GEN-LAST:event_B_DiviActionPerformed

    
    private void Op (double num1, double num2){
        switch (TOperaciones) {
            case "+":
                resultado = num1+num2;
                jTextField_Principal.setText(String.valueOf(resultado));
                num1 = Double.parseDouble(jTextField_Principal.getText());
                break;
            case "-":
                resultado = num1-num2;
                jTextField_Principal.setText(String.valueOf(resultado));
                num1 = Double.parseDouble(jTextField_Principal.getText());
                break;
            case "*":
                resultado = num1*num2;
                jTextField_Principal.setText(String.valueOf(resultado));
                num1 = Double.parseDouble(jTextField_Principal.getText());
                break;
            case "/":
                if (num1 == 0 || num2 ==0){
                    jTextField_Principal.setText("Error");
                }else{
                    resultado=(double)(num1/num2);
                    jTextField_Principal.setText(String.valueOf(resultado));
                num1 = Double.parseDouble(jTextField_Principal.getText());
                }

                break;
            default:
                jTextField_Principal.setText("Error");
        }
    }
    
    
    private void B_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IgualActionPerformed
       
        inicio = true;
        op1=true;
        if (igual =true){
            if (TOperaciones == null){
                
            }else{
                num2= Double.parseDouble(jTextField_Principal.getText());
                Op (num1,num2);
                igual = false;
            }  
        } else {
          
        }
    }//GEN-LAST:event_B_IgualActionPerformed

    
    private void B_RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RaizActionPerformed
   
        num1= Double.parseDouble(jTextField_Principal.getText());
        if (num1>=0){
            jTextField_Principal.setText(String.valueOf(Math.sqrt(num1)));
        }else{
            jTextField_Principal.setText("Error");
        }
    }//GEN-LAST:event_B_RaizActionPerformed

    
    private void B_PorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PorceActionPerformed
       
        num2= Double.parseDouble(jTextField_Principal.getText());
        jTextField_Principal.setText(String.valueOf((num1*num2)/100));
        igual= true;
    }//GEN-LAST:event_B_PorceActionPerformed

 
    private void B_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarActionPerformed
      
        String texto = jTextField_Principal.getText();
    if (texto.length() > 1) {
        texto = texto.substring(0, texto.length() - 1);
        jTextField_Principal.setText(texto);
            inicio = true;
        }else {
            jTextField_Principal.setText("0");
        }

    }//GEN-LAST:event_B_BorrarActionPerformed

    private void B_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LimpiarActionPerformed
       
        jTextField_Principal.setText("0");
        inicio= true;
        op1=true;
        op2=true;
        igual=true;
        num1=0;
        num2=0;
        resultado=0;
    }//GEN-LAST:event_B_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraCientifica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_0;
    private javax.swing.JButton B_1;
    private javax.swing.JButton B_2;
    private javax.swing.JButton B_3;
    private javax.swing.JButton B_4;
    private javax.swing.JButton B_5;
    private javax.swing.JButton B_6;
    private javax.swing.JButton B_7;
    private javax.swing.JButton B_8;
    private javax.swing.JButton B_9;
    private javax.swing.JButton B_Borrar;
    private javax.swing.JButton B_Divi;
    private javax.swing.JButton B_Igual;
    private javax.swing.JButton B_Limpiar;
    private javax.swing.JButton B_Multi;
    private javax.swing.JButton B_Porce;
    private javax.swing.JButton B_Punto;
    private javax.swing.JButton B_Raiz;
    private javax.swing.JButton B_Rest;
    private javax.swing.JButton B_Sum;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Principal;
    private javax.swing.JTextField jTextField_Principal1;
    // End of variables declaration//GEN-END:variables
}
